### ISSUE TITLE
InvalidPathException on Windows

### ISSUE THREAD

**Issue by vgcpge** [vgcpge/eclipse.copilot#28]
Automatic download of Copilot fails on Windows:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Program Files/Eclipse Foundation/Eclipse IDE for Java EE Developers/configuration/\org.vgcpge.eclipse.copilot.ui
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at org.vgcpge.eclipse.copilot.ui.internal.Configuration.getPersistentStorage(Configuration.java:96)
	at org.vgcpge.eclipse.copilot.ui.internal.GithubCopilotProvider.start(GithubCopilotProvider.java:59)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$0(LanguageServerWrapper.java:266)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
```

**Comment by vgcpge** [comment]
@FriedrGo please see if fixed version from [update site archive](https://github.com/vgcpge/eclipse.copilot/suites/14357500838/artifacts/808552954) fixes the problem for you

**Comment by vgcpge** [comment]
A new problem happens on Windows: #30
